### PR TITLE
Peach-Probe For Peach-Stats & Peach-Oled

### PR DESCRIPTION
**Pull request by mhfowler**
This is a (possibly) full implementation of peach-probe for all the endpoints on peach-stats and peach-oled. 

I thought it would be good to write two microservices, to check the general pattern, and then I can extend it to the other microservices. 

The major changes since our pair programming session:
- Keeping a list of strings of successes & failures so there is a nicer output at the end of any failures that occurred 
- Abstracted some of the code into functions probe_stats_endpoint and probe_oled_endpoint to reduce duplicate code (perhaps the cleanest way to do this, would actually be to bundle the Error types of OledError and StatsError together someway, and then just have one probe_endpoint function that gets used by both, since they are essentially the same)
- Added the enum_arg feature you found for better structopt help and error messages 

if this looks good, or with any feedback, then maybe it would be good to merge this in before adding all the other microservices?

### CODE REVIEW

**Comment by mhfowler** [comment]
@mycognosist also one small question 
- I noticed that the power endpoint on peach-oled expected a parameter called "on" 
but it looked to me like peach-lib might be passing a parameter named power https://github.com/peachcloud/peach-lib/blob/main/src/oled_client.rs#L139 . Although I might be misreading how jsonrpc_client works. wondering if you have a recommended way to debug exactly what underlying requests are actually being sent to a microservice? ... I can also google around more about the jsonrpc library to get a better feel for it

**Comment by mycognosist** [comment]
@mhfowler 

Good catch! The parameter should indeed be `on` and not `power`. I've fixed the issue: https://github.com/peachcloud/peach-lib/pull/5

> wondering if you have a recommended way to debug exactly what underlying requests are actually being sent to a microservice?

I don't know of a neat inline way of doing this. One simple solution is to use `netcat`:

`nc -l -p 5113`

That command just sets up a simple TCP listener on port 5113. Here's the output of an RPC call made using `curl`:

```
POST / HTTP/1.1
Host: 127.0.0.1:5113
User-Agent: curl/7.64.0
Accept: */*
Content-Type: application/json
Content-Length: 47

{"jsonrpc": "2.0", "method": "uptime", "id":1 }
```

The downside of this approach is that an actual RPC client implementation expects a response from the server. Since the `netcat` listener doesn't respond, this method is only really useful for debugging a single RPC call at a time.

**Comment by mycognosist** [comment]
@mhfowler 

This is looking really good - nice work! I can see how the creation of a unified error type will prevent the need for multiple `probe_x_endpoint` functions. I think let's go ahead and merge this PR and you can continue implementing the probes for the other client (it's basically just `peach-network` at this point, if I'm not mistaken). Once I've figured out the unified error type we can talk through that and implement it :)

One small note about the probe behavior for `peach-oled`: rearranging the order of the client calls will prevent any text actually being displayed on the OLED (an artifact we wish to avoid), while still successfully probing each endpoint. In the existing code, `flush` is called after `write` which means that the text ends up on the display. I think it would be better to call the endpoints in the following order: `ping`, `write`, `clear`, `flush`. Using this order means the `peach-probe` run will not have any visible effect on the OLED display.

**Comment by mycognosist** [comment]
> perhaps the cleanest way to do this, would actually be to bundle the Error types of OledError and StatsError together someway, and then just have one probe_endpoint function that gets used by both, since they are essentially the same

After thinking about this for a little while I realized that the best solution was to export a unified error type from `peach-lib`, rather than doing the unification in `peach-probe`:

https://github.com/peachcloud/peach-lib/pull/6

The path is now clear for you to refactor `peach-probe` to use a single `probe_endpoint` function. You'll need to ensure the `peach-lib` dependency in your `Cargo.toml` file is pointed to the `main` branch (the latest version is 1.1.0).

Happy coding!

**Pull request merged**
