### PR TITLE
Still a work in progress, creating PR for discussion; Basic CLI with structopt + peach-stats probe 

### PR DESCRIPTION
**Pull request by mhfowler**
getting started, getting started 

as I mentioned here, https://github.com/peachcloud/peach-probe/issues/1, 
I have some question about how best to break out the json-rpc-client code. 

For now I've put it into its own file, directly copied from peach-web -- so this could remain as it is (part of peach-probe) or easily substituted for an external peach-lib crate that is included. 

I also have some more questions, that I included as a comment at the bottom stats_probe.rs and will also include here:

    // how should peach-probe return its results to the user
    // and how does this interact with levels of verbosity?
    // - I assume peach-probe should continue probing after it encounters an error,
    // so it shouldn't just panic and end
    // - should errors be stored in some type of data structure that gets passed around?
    // so that in the end, a sort of final report can be generated of what is online
    // and what is offline?
    // - and/or should there be printed feedback?
    // - for handling levels of verbosity, should we use the logging system (debug/info/warn), and have
    // the level of verbosity simply change the log level
    // or should we write a sort of custom log function, that decides what to do, based
    // on the verbosity that is set

_________________

I also have another set of questions about structopt. 

I figured out an implementation that is working,
and I like your suggestion in the other issue to handle ports with env variables (also so it is the same across peach services, relating again to the above peach-lib idea), 

but I'm also not sure I'm using structopt in the ideal way, 
maybe there would be an easier way to do what I'm trying to do and could have nicer error messages for sure 
that actually tells the user what their options are for microservices, 
instead of just saying they picked a bad one

### CODE REVIEW

**Comment by mhfowler** [comment]
also was really nice using the deploy.sh script for this, 
once the probe_stats function was written, 
I could run it on my laptop and see that it returns an error (peach-stats isn't running on my laptop)
and then run deploy.sh and it would run on the pi and show that peach-stats was online

**Comment by mycognosist** [comment]
@mhfowler 

As general advice / feedback I'd say take things one step at a time. For example, I wouldn't worry about verbosity for the time being. Start by implementing the basic probe functionality for a single microservice and see how that feels. The basic working version will then allow us to use it and identify which additional information we would like to have (this can then inform the determination of the verbosity levels). So perhaps the most basic version just hits all the API endpoints of a given microservice and reports if there are any errors (like: `cpu_stats` returned an error). An additional layer of verbosity might include the error code and message for the failed request.

> I assume peach-probe should continue probing after it encounters an error, so it shouldn't just panic and end

Correct.

> should errors be stored in some type of data structure that gets passed around?

I don't think this is necessary. Each RPC client already implements a custom error type. Once we have the client code organised in the new `peach-lib` repo, the error types can simply be imported into `peach-probe` and used to match on the responses. Then you can utilise the existing code which conveniently has nice error messages (ie. "Failed to retrieve CPU statistics: <underlying error>"). You can store the errors in a `struct` or other data structure for the purposes of final reporting. Perhaps it's best to work through this together in a pair session.

> I'm also not sure I'm using structopt in the ideal way

I'm going to look carefully at what you've implemented so far and suggest any changes.

**Comment by mycognosist** [comment]
@mhfowler 

Another suggestion is to make sure you're running `cargo fmt` and `cargo clippy` against your code updates before any commits (you might even want to customise your dev env so that they're run automatically each time you save). `fmt` will clean up your code formatting so that we have uniform formatting across the codebase. `clippy` will catch inelegant / inefficient code and suggest changes, for example:

```
warning: length comparison to zero
  --> src/main.rs:74:8
   |
74 |     if opt.services.len() == 0 {
   |        ^^^^^^^^^^^^^^^^^^^^^^^ help: using `is_empty` is clearer and more explicit: `opt.services.is_empty()`
   |
```

**Comment by mycognosist** [comment]
@mhfowler 

A few more thoughts on the question of reporting:

For now, I like the way you are simply handling reporting in `stats_probe.rs`. It's a self-contained approach which reports as it goes. I think this kind of output is perfectly sufficient for what we're trying to achieve (at least for the first pass).

If you wanted to collect the results in order to initiate some final reporting from `src/main.rs`, you might return a `Result` type from the `probe_stats()` function - one which returns `Ok(())` if all RPC endpoint calls are successful or a `Vec<Err>` if any errors are encountered. You can then match on the `Result` in the calling code and use the returned data for report compilation.

As mentioned in a previous comment, I think working through this together on a call will yield clarity and a solid solution.

**Comment by mhfowler** [comment]
will save responding to any of this since we will talk over a call tomorrow, but thanks for the review!

**Comment by mycognosist** [comment]
@mhfowler 

I found a solution to the `structopt` argument enumeration we were wondering about :)

Check this out:

[enum_in_args](https://github.com/TeXitoi/structopt/blob/0c888e962d842f2c90c6c290d3a2a40947b37005/examples/enum_in_args.rs) example. I found it by way of this StackOverflow post: [How can I use enums in structopt in Rust?](https://stackoverflow.com/a/58171404)

This approach uses the `arg_enum!` macro from the [clap crate](https://crates.io/crates/clap) and removes the need for the custom `FromStr` implementation. I guess the major trade-off is the added `clap` dependency.

I just tested it out and `peach-probe` now enumerates the possible `service` options in the help menu (at the bottom):

```
ARGS:
    <services>...     [possible values: Oled, Network, Stats, Menu]
```

And in the case of an incorrect / unsupported entry:

```
./peach-probe men
error: 'men' isn't a valid value for '<services>...'
	[possible values: Menu, Network, Oled, Stats]
```

**Comment by mhfowler** [comment]
@mycognosist It looks like using this you just get one argument (e.g. `peach-probe network`). I can look into nesting this within a vector, to allow for `peach-probe network oled`, but wondering if that will play nicely with the autogenerated error or  help message. But maybe thats not an important feature anyway and its more relevant to filter down to one microservice than a particular subset?

**Comment by mhfowler** [comment]
@mycognosist I'm also not sure how to use the arg_enum within an option (for an  optional argument). I would be curious! but I've also now got a working solution using the original way but customizing the help and error message to list the possible options

**Comment by mycognosist** [comment]
@mhfowler 

> It looks like using this you just get one argument (e.g. peach-probe network)

Nope, it works with any number of arguments. Here's my working implementation:

```rust
#[derive(StructOpt, Debug)]
 #[structopt(
     name = "peach-probe",
     about = "a CLI tool for contract testing of the public API's exposed by PeachCloud microservices"
 )]
 struct Opt {
     #[structopt(short, long)]
     verbose: bool,
     #[structopt(possible_values = &Microservice::variants(), case_insensitive = true)]
     services: Vec<Microservice>,
 }
 
 arg_enum! {
     #[derive(Debug)]
     enum Microservice {
         Oled,
         Network,
         Stats,
         Menu,
     }
 }
```

The rest of the code (ie. `fn main()`) remains as it was before.

Personally, I like the elegance of this approach. It offers a clean implementation without needing to customize the help and error messages.

**Comment by mhfowler** [comment]
oh nice! I was misreading an error message, oops / cool

**Pull request closed without merging**
