### PR TITLE
Combine errors into PeachError, and working on peach-probe for peach-network

### PR DESCRIPTION
**Pull request by mhfowler**
@mycognosist 

I merged the previous pull request and started a new one with the rest of the work. 

I have a bunch of questions:

1. It seems to me there is kind of convention elsewhere of calling microservices peach-oled peach-stats peach-network (e.g. those are the package names). 
... my feeling is it would be natural to continue that convention here, and in peach-probe refer to the microservices with that naming instead of just Stats Newtork Oled, but if you feel its better the other way I can do either 

2. do we just want to probe peach-network peach-stats and peach-oled? we don't want to probe peach-menu and/or other services? still getting a feel here for what all the services do

3. serde doesn't implement description for their error message,
is there another way we should get the error message to display for Serde errors? this also relates to the point below

4. e.description() gives not very informative error message, like:
Returned JsonRpcCore error: "Unable to send the JSON-RPC 2.0 request"

if we just do:
  `PeachError::JsonRpcCore(e) => eprintln!("Returned JsonRpcCore error: {:?}\n", e)`,
--> we get a more informative error message, like:
Returned JsonRpcCore error: Error(JsonRpcError(Error { code: ServerError([ probing stats microservice ]
-32013), message: "Failed to open control interface for wpasupplicant: Address family not supported by protocol (os error 97)", data: None }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
.... for instance while I was debugging not working endpoints, which is what i imagine one might do after the probe fails some endpoints, getting a bit more information on the error was actually helpful. 

5. the visual artifact you wrote about on the other PR -- I can see why you would want to have no visual trace, but I could also see it not as a visual artifact, but as a nice source of feedback that the display is working (which is maybe what you want from peach-probe?). But again could see either way 

6. I've started with peach-network and I'm seeing some errors on the microservice. I've been trying to debug them for a while but I'm a little stuck. 

The errors so far are on the add endpoint and available_networks endpoint

```
++ available_networks endpoint is offline
{"jsonrpc":"2.0","error":{"code":-32013,"message":"Failed to open control interface for wpasupplicant: Address family not supported by protocol (os error 97)"},"id":1}

++ add endpoint is offline
Returned JsonRpcCore error: Error(TransportError, State { next_error: Some(Error(Hyper(Incomplete), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })
```

I believe I started seeing these errors after calling the add endpoint with a test string "test-ssid" and "testpass". 
I think available_networks was working before then. 
I think it may be some type of permission issue... but I haven't figured it out yet and taking a break... maybe you have some ideas?

### CODE REVIEW

**Comment by mhfowler** [comment]
also, when I re-compile peach-network on the VPS, and then run it on my pi directly as a binary, I get the error
```
[2020-12-10T13:37:06Z INFO  peach_network] Starting JSON-RPC server on 127.0.0.1:5110.
thread 'jsonrpc-eventloop-0' panicked at 'attempted to leave type `std::mem::ManuallyDrop<internal::SealedBag>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658:9
```

I wonder if this is perhaps related to the other errors I was seeing before with some of the microservices being compiled on the VPS and not running on the pi ... another reason for me to try installing linux on my laptop (for sanity check)

**Comment by mycognosist** [comment]
@mhfowler 

1. I agree with your suggested approach of continuing the `peach-____` convention

2. Yes, for now we just need the `peach-network`, `peach-oled` and `peach-stats` microservices to be covered by `peach-probe`. Those three microservices behave as servers which handle requests and send responses. `peach-buttons` and `peach-menu` also utilise JSON-RPC but their behaviour is a bit different:

- `peach-buttons` functions as a pub-sub service which functions over a websocket; each button press results in the publication of a JSON-RPC message
- `peach-menu` subscribes to `peach-buttons` and uses the received JSON-RPC messages as input for a state machine. The state machine controls what is displayed on the OLED display by calling `peach-network` and `peach-stats` (to obtain device data) and then calling `peach-oled` (to display the retrieved data)

    With that in mind, I think the best way to ensure correct functioning of `peach-buttons` and `peach-menu` is to write more unit tests and to combine those automated tests with manual testing (this is particularly important with anything involving input buttons since they may exhibit unwanted behaviour which is not apparent from automated testing, for example: one button press resulting in multiple interrupts - a problem which is solved via debouncing).

3. The serde error is an edge-case which is highly unlikely to occur in our existing implementation (I've questioned whether it should be exported as part of PeachError or kept as an internal error which is not communicated to any clients of the `peach-stats` microservice). For the purposes of `peach-probe`, I think it's sufficient to print something like: `serde serialization error`

4. I like your suggested approach of printing `e` to return a more informative error message. You can utilise `{:#?}` in your formatting of the output, instead of the current `{:?}`. This is referred to as pretty-printing and will include line-breaks and indentation in the output (particularly helpful when displaying `structs` with multiple fields). An example and further details can be found in [listing 5-12 of the Rust book](https://doc.rust-lang.org/book/ch05-02-example-structs.html#adding-useful-functionality-with-derived-traits)

5. I hear what you're saying about the visual feedback. I first noticed it on my OLED display when I ran `peach-probe` on my Pi. The result was `Running peach-probe` overlaid with the PeachCloud logo (the 'splash page' of the menu). That felt untidy to me. My opinion is that, ideally, any fault with `peach-oled` should be caught by `peach-probe` and that `peach-probe` should leave the system in the same state it was in prior to execution

6. I'm going to take some time to investigate the `peach-network` errors (including those seemingly coming as a result of VPS-based compulation) before responding more fully

Thanks so much for all this great work you're doing and for communicating so clearly 🙏🏻 🖤

**Comment by mycognosist** [comment]
@mhfowler 

I've forked the networking error discussion to [this issue in the peach-network repo](https://github.com/peachcloud/peach-network/issues/8).

**Comment by mhfowler** [comment]
@mycognosist 

while the other microservices are not running on my pi, I decided I would start finishing off peach-network in peach-probe which is running 

many of the endpoints are working, but here are the issues I encountered and have questions about - whether they require changes to peach-network or something else. 

1. network::connect
Returned JsonRpcCore error: Error(JsonRpcError(Error { code: ServerError(-32027), message: "Failed to connect to network wlan0 for peach-probe-test-ssid", data: None }), [ generating report ]
State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })

... I was running it with arguments:
network_client::connect("peach-probe-test-ssid", "wlan0")
, which is not a real network. 

Should I catch this error in peach-probe, and if its the correct error, declare that the endpoint is online?
As its not a real wifi ssid used for peach-probe, this endpiont shouldn't really be able to succeed

2. there is a similar issue here for: 
ssid which returns:
message: "Failed to retrieve SSID for wlan0. Interface may not be connected

3.
status, RSSI, rssi-percent all throw this error:
Returned JsonRpcCore error: Error(TransportError, State { next_error: Some(Error(Hyper(Incomplete), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })

perhaps I am using them incorrectly? or is it similar to the above errors (doesn't work when wifi isn't actually connected), and maybe we just need a more informative message?

4.
disable, disconnect, delete, save, reconnect, modify 
all are defined in network_client.rs (at the bottom)
but are not actually implemented in thefile. 
should these methods be implemented, or possibly should the definitions also be removed? or can just comment these out in peach-probe as "not yet implemented

5. last small detail note, 
while I wanted to change the arguments for the CLI to be like peach-network or peach-oled to match the rest of the documentation (instead of oled and network), it looks to me like StructOpts would not like us using a hyphen in the name so the arg names currently are peachnetwork and peacholed ... which is maybe a little weird? I will just make it whatever you prefer, I don't have a preference

**Comment by mycognosist** [comment]
@mhfowler 

1. The error you receive for the `connect` RPC is correct and expected. This method would be used to connect to an access point for which credentials (SSID and password) have already been added. It's useful in a case where the peach device is in-range of several access points for which credentials are stored, and you wish to switch between them. It's also used to make the initial connection attempt to an AP after the credentials have been saved in `wpa_supplicant.conf`.

    The ordering of the error message is a bit clunky. It would probably read more clearly if the interface and SSID were swapped. Perhaps like this: `Failed to connect to network peach-probe-test-ssid on wlan0`
    
    If you're running `peach-probe` with a made-up SSID and you receive this error response, I think it's correct to catch the error and mark the endpoint as online (or use some other means of communicating that the endpoint is behaving as expected).
    
2. Same as above: the endpoint is online and behaving as expected if it returns an error with code `-32003` (`Failed to retrieve SSID for {_}. Interface may not be connected`). If the endpoint returns a different error then the endpoint should appear as offline (this might indicate a permissions error, for example).

3. These methods could all use improved error-handling. Right now they are panicking when queried while `wlan0` is not connected to an AP (a case of lazy error-handling on my behalf). I'll prepare a PR to `peach-network` to improve this.

4. There are a few variations here (relating to `peach-lib/src/network_client.rs`):

    - `disable` is implemented as a client call (at the bottom) and as a standalone function
    - `delete` is implemented as a client call and is invoked from within several functions (e.g. `pub fn forget` and `pub fn update`), though it does not have a dedicated `pub fn` for itself
    - `save` is implemented as a client call and is invoked from within several functions (e.g. `pub fn forget` and `pub fn update`), though it does not have a dedicated `pub fn` for itself
    - `disconnect`, `reconnect` and `modify` are not currently implemented in `peach-lib` but they do exist as part of the `peach-network` API. I think the best thing to do for now is to remove the definitions from `peach-lib`. These would have been RPC calls which I initially added to `peach-network` but which are not currently required by `peach-menu` or `peach-web` (though they may prove useful in the future).

5. > it looks to me like StructOpts would not like us using a hyphen in the name so the arg names currently are peachnetwork and peacholed

    Are underscores accepted? That would be my preference in terms of readability, ie. `peach_network` and `peach_oled`

**Comment by mhfowler** [comment]
I think there may be a lot of things here I've done which are not idiomatic to rust (still a lot of learning to do but this was a great task for starting to get familiar), 
but feature-wise I think everything is here other than displaying what error happened on startup, if an error was found with systemctl status for a service. 

Things included so far:
- change CLI args to use underscore 
- use systemctl status to check if a service is running 
- clean up final report 

Perhaps I can add the display of error message, and then we can do another code review and maybe clean some things up

**Comment by mhfowler** [comment]
right now the output of the final report looks like this for me:
```
[ generating report ]
- peach-network [version: 0.2.4] is online.
- peach-oled [version: 0.1.0] is online.
- peach-web [version: 0.3.1] is online.
- peach-buttons [version: 0.1.2] is online.
- peach-menu [version: 0.2.5] is online.
- peach-stats [version: 0.1.0] failed to start, with error: Unknown Error
- peach-monitor [version: 0.1.0] failed to start, with error: Unknown Error
```

**Comment by mhfowler** [comment]
I like how its getting to a place which is pretty concise and would be easy to share

**Comment by mhfowler** [comment]
Ok I've now made it so if the service is not running according to systemctl status, the probe queries journalctl -u, and includes the last 3 lines of that log as part of the report (this is essentially replicating the way I have been manually debugging what services are running on my pi) 

When there is an error this makes the output slightly less beautiful, but perhaps informative, e.g.
```
[ generating report ]
- peach-network [version: 0.2.4] is online.
- peach-oled [version: 0.1.0] is online.
- peach-web [version: 0.3.1] is online.
- peach-buttons [version: 0.1.2] is online.
- peach-menu [version: 0.2.5] is online.
- peach-stats [version: 0.1.0] is offline, with log:
 -- Logs begin at Thu 2019-02-14 10:11:59 UTC, end at Wed 2020-12-30 14:41:37 UTC. --
Dec 30 11:33:58 peach peach-stats[469]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dec 30 11:33:59 peach peach-stats[474]: thread 'http.worker00' panicked at 'attempted to leave type `std::mem::ManuallyDrop<internal::SealedBag>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658:9
Dec 30 11:33:59 peach peach-stats[474]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

- peach-monitor [version: 0.1.0] is offline, with log:
 -- Logs begin at Thu 2019-02-14 10:11:59 UTC, end at Wed 2020-12-30 14:41:39 UTC. --
-- No entries --
```

As mentioned I think this code may be a bit messy, was definitely learning and making at the same time, 
very open to feedback and to revise things.

**Comment by mycognosist** [comment]
@mhfowler 

This is terrific progress. I really like how the report is coming together! I'm happy that this has been such a great task for you to learn and explore.

> As mentioned I think this code may be a bit messy, was definitely learning and making at the same time,
very open to feedback and to revise things.

The first thing I notice is the way you're using paths. I suggest reading through this page of the Rust Book: [Bringing Paths into Scope with the use Keyword](https://doc.rust-lang.org/stable/book/ch07-04-bringing-paths-into-scope-with-the-use-keyword.html).

In a nutshell, we want to be bringing paths into scope at the top of each source file. This minimizes code repetition while also making it easier to see which dependencies the code is using at a glance. An example from `src/probe.rs`:

There are three functions where you call `std::process::Command::new()` as follows:

```rust
let output = std::process::Command::new("/usr/bin/apt")
             .arg("list")
             .arg(service)
             .output()?;
```

Instead, define the path at the top of the file and then call it with a more concise path:

```rust
use std::process::Command;

let output = Command::new("/usr/bin/apt")
             .arg("list")
             .arg(service)
             .output()?;
```

These improvements can be made in `src/probe.rs` and `src/error.rs` (I don't see any unidiomatic examples in `src/main.rs`). The Rust Book defines the conventions for functions, objects, naming clashes etc.

**Comment by mycognosist** [comment]
@mhfowler 

I happened to look at `/etc/wpa_supplicant/wpa_supplicant.conf` on my Pi and noticed that running `peach-probe` does not remove the `peach-probe-test-ssid` network after probing the `network_client::add()` endpoint. This results in multiple copies of the network credentials being stored in the config file:

```bash
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=wpactrl-user
update_config=1
network={
        ssid="peach-probe-test-ssid"
        #psk="peach-probe-test-pass"
        psk=af05de13ba1711ddbd04ab0feeb5250428f06e0072115eff4c71e659f4aa4d5a
}
network={
        ssid="peach-probe-test-ssid"
        #psk="peach-probe-test-pass"
        psk=af05de13ba1711ddbd04ab0feeb5250428f06e0072115eff4c71e659f4aa4d5a
}
network={
        ssid="peach-probe-test-ssid"
        #psk="peach-probe-test-pass"
        psk=af05de13ba1711ddbd04ab0feeb5250428f06e0072115eff4c71e659f4aa4d5a
}
```

My recommendation for fixing this would be to probe the [`network_client::forget()` endpoint](https://github.com/peachcloud/peach-lib/blob/fada5b466763d16cdc3337178087d42b09a679a9/src/network_client.rs#L182) after probing the `network_client::add()` endpoint. That should remove the network credentials from `wpa_supplicant.conf` and save the change.

**Comment by mhfowler** [comment]
@mycognosist just pushed a small commit which 

- forgets the peach-probe-test-ssid after it is added so it doesn't clog up the wpa_supplicant file (just tested and its working) 
- brings Command into scope as described in your code review 

getting close to merge I think, but have two questions:

1. we were having a discussion before about if peach-probe should leave anything on the screen and you said it would be best for peach-probe to have no visual artifact and we could do this by adding a .clear() at the end. 
this works, except it doesn't leave the peach in the state it was in before, e.g. before it is displaying something, then you run peach-probe, then it is displaying nothing. to me this still kind of looks like an error, or there is this feeling "did it work?" 
so it feels like to me calling .clear at the end still leaves a visual artifact, because it erases whatever was there before. so if its still leaving some visual artifact either way, 
Right now I call .clear at the beginning, so regardless of the previous state, there is no overlapping writing, and it doesn't look messy, but there is a visual at the end showing that it ran. unless the rest of peach web expects the screen to be clear to begin with? although I imagine it would be good if display code was idempotent where possible and would work regardless of the previous state of the display. but let me know if you think blank screen still makes more sense than a success message, even if we can't preserve the original state. 

2. the disable endpoint is throwing an error which I'm catching, but it doesn't sound like the error it should be throwing? 
When I call ```network_client::disable("peach-probe-test-ssid", "wlan0")```
the error message is:
```Failed to open control interface for wpasupplicant: Address already in use (os error 98)```

After resolving these two issues, + anything else you think of, then I would merge the PR

**Comment by mhfowler** [comment]
I would also add these as 2 separate (small) tasks after merging this (just noting this here):
- re-add status, RSSI, rssi-percent probe, after someone makes a PR to peach-network to change the error-handling for these methods 

- remove disconnect, reconnect and modify from peach-lib,
per glyph's comment here:
https://github.com/peachcloud/peach-probe/pull/6#issuecomment-751667513

**Comment by mhfowler** [comment]
or I guess to not effect the state of the oled, we could call clear at the end without calling flush? maybe that's what you originally suggested I forget

**Comment by mhfowler** [comment]
just tested and see that clear even without flush also seems to clear the screen

**Comment by mycognosist** [comment]
@mhfowler 

> Right now I call .clear at the beginning, so regardless of the previous state, there is no overlapping writing, and it doesn't look messy, but there is a visual at the end showing that it ran

I'm happy with this outcome and agree with you that it might be confusing if there's simply a blank display after running `peach-probe`. Definitely seems better to have some indication of success.

A bit of insight into the menu system: Any direct calls to the `peach-oled` microservice do not alter the internal state of the OLED menu system. Instead, state is managed by the `peach-menu` service. So, as far as the menu state machine is concerned, the OLED calls made by `peach-probe` never happen. This means that any button press events occurring after `peach-probe` will update the menu state and draw to the display accordingly, based on the last known state.

> just tested and see that clear even without flush also seems to clear the screen

That's right. This is because the `clear()` RPC call bundles `clear` and `flush` for convenience ([source](https://github.com/peachcloud/peach-oled/blob/acdf727d14bd6354e57687cb97aba241bfb2121d/src/lib.rs#L125)).

> re-add status, RSSI, rssi-percent probe, after someone makes a PR to peach-network to change the error-handling for these methods

I'm going to turn my attention to the error-handling changes now. Will let you know once they're in place.

> the disable endpoint is throwing an error which I'm catching, but it doesn't sound like the error it should be throwing?

Thanks for the heads-up! I'll take a look at this.

**Comment by mhfowler** [comment]
@mycognosist for peace of mind (and to-do list) I would vote to merge this in, 
and then return to it later after working on peach-network more to make sure everything is still working,
and to add any of the missing endpoints that needed more detailed error messages 
(status, RSSI, rssi-percent, disable)

does that sound ok?

**Comment by mycognosist** [comment]
@mhfowler 

> for peace of mind (and to-do list) I would vote to merge this in

I completely agree. You're welcome to merge at your leisure : )

**Pull request merged**
